title: Site

tabs:

  index:
    label: Index
    icon: dashboard

    columns:

      - width: 1/2
        sections:

          listed:
            headline: Pages
            extends: sections/pages
            status: listed
            create: false
            sortable: false
            # info: "{{ page.children.listed.count }}"
